// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: daemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	DiscoveryPort int32                  `protobuf:"varint,3,opt,name=discovery_port,json=discoveryPort,proto3" json:"discovery_port,omitempty"`
	RecvDir       string                 `protobuf:"bytes,4,opt,name=recv_dir,json=recvDir,proto3" json:"recv_dir,omitempty"`
	AutoAccept    bool                   `protobuf:"varint,5,opt,name=auto_accept,json=autoAccept,proto3" json:"auto_accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Config) GetDiscoveryPort() int32 {
	if x != nil {
		return x.DiscoveryPort
	}
	return 0
}

func (x *Config) GetRecvDir() string {
	if x != nil {
		return x.RecvDir
	}
	return ""
}

func (x *Config) GetAutoAccept() bool {
	if x != nil {
		return x.AutoAccept
	}
	return false
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LastSeen      string                 `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Peer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Peer) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *PeerList) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	TargetIp      string                 `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *SendFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SendFileRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

type ReceivedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	SenderIp      string                 `protobuf:"bytes,3,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedFile) Reset() {
	*x = ReceivedFile{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedFile) ProtoMessage() {}

func (x *ReceivedFile) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedFile.ProtoReflect.Descriptor instead.
func (*ReceivedFile) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ReceivedFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReceivedFile) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *ReceivedFile) GetSenderIp() string {
	if x != nil {
		return x.SenderIp
	}
	return ""
}

type ReceivedFileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*ReceivedFile        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedFileList) Reset() {
	*x = ReceivedFileList{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedFileList) ProtoMessage() {}

func (x *ReceivedFileList) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedFileList.ProtoReflect.Descriptor instead.
func (*ReceivedFileList) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ReceivedFileList) GetFiles() []*ReceivedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\x06daemon\"\a\n" +
	"\x05Empty\"\x93\x01\n" +
	"\x06Config\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12%\n" +
	"\x0ediscovery_port\x18\x03 \x01(\x05R\rdiscoveryPort\x12\x19\n" +
	"\brecv_dir\x18\x04 \x01(\tR\arecvDir\x12\x1f\n" +
	"\vauto_accept\x18\x05 \x01(\bR\n" +
	"autoAccept\"O\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\tR\blastSeen\".\n" +
	"\bPeerList\x12\"\n" +
	"\x05peers\x18\x01 \x03(\v2\f.daemon.PeerR\x05peers\"K\n" +
	"\x0fSendFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\ttarget_ip\x18\x02 \x01(\tR\btargetIp\"i\n" +
	"\fReceivedFile\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\vreceived_at\x18\x02 \x01(\tR\n" +
	"receivedAt\x12\x1b\n" +
	"\tsender_ip\x18\x03 \x01(\tR\bsenderIp\">\n" +
	"\x10ReceivedFileList\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.daemon.ReceivedFileR\x05files2\xba\x02\n" +
	"\rDaemonService\x12*\n" +
	"\tSetConfig\x12\x0e.daemon.Config\x1a\r.daemon.Empty\x12*\n" +
	"\tGetConfig\x12\r.daemon.Empty\x1a\x0e.daemon.Config\x12,\n" +
	"\tListPeers\x12\r.daemon.Empty\x1a\x10.daemon.PeerList\x121\n" +
	"\x11BroadcastPresence\x12\r.daemon.Empty\x1a\r.daemon.Empty\x122\n" +
	"\bSendFile\x12\x17.daemon.SendFileRequest\x1a\r.daemon.Empty\x12<\n" +
	"\x11ListReceivedFiles\x12\r.daemon.Empty\x1a\x18.daemon.ReceivedFileListB\bZ\x06/protob\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_daemon_proto_goTypes = []any{
	(*Empty)(nil),            // 0: daemon.Empty
	(*Config)(nil),           // 1: daemon.Config
	(*Peer)(nil),             // 2: daemon.Peer
	(*PeerList)(nil),         // 3: daemon.PeerList
	(*SendFileRequest)(nil),  // 4: daemon.SendFileRequest
	(*ReceivedFile)(nil),     // 5: daemon.ReceivedFile
	(*ReceivedFileList)(nil), // 6: daemon.ReceivedFileList
}
var file_daemon_proto_depIdxs = []int32{
	2, // 0: daemon.PeerList.peers:type_name -> daemon.Peer
	5, // 1: daemon.ReceivedFileList.files:type_name -> daemon.ReceivedFile
	1, // 2: daemon.DaemonService.SetConfig:input_type -> daemon.Config
	0, // 3: daemon.DaemonService.GetConfig:input_type -> daemon.Empty
	0, // 4: daemon.DaemonService.ListPeers:input_type -> daemon.Empty
	0, // 5: daemon.DaemonService.BroadcastPresence:input_type -> daemon.Empty
	4, // 6: daemon.DaemonService.SendFile:input_type -> daemon.SendFileRequest
	0, // 7: daemon.DaemonService.ListReceivedFiles:input_type -> daemon.Empty
	0, // 8: daemon.DaemonService.SetConfig:output_type -> daemon.Empty
	1, // 9: daemon.DaemonService.GetConfig:output_type -> daemon.Config
	3, // 10: daemon.DaemonService.ListPeers:output_type -> daemon.PeerList
	0, // 11: daemon.DaemonService.BroadcastPresence:output_type -> daemon.Empty
	0, // 12: daemon.DaemonService.SendFile:output_type -> daemon.Empty
	6, // 13: daemon.DaemonService.ListReceivedFiles:output_type -> daemon.ReceivedFileList
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
